import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { StyledRoot } from "./components/StyledRoot";
import { ApolloWrapper } from "@/lib/apolloWrapper";


/* const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ApolloWrapper>
          <AppRouterCacheProvider>
            <StyledRoot>
              {children}
            </StyledRoot>
          </AppRouterCacheProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
