'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { theme, darkTheme } from "@/theme";
import { ThemeProvider } from '@mui/material/styles';
import { useState } from "react";
import Navbar from "./components/Navbar";


/* const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isDarkTheme, setTheme] = useState(false)
  return (
    <html lang="en">
      <body style={{ margin: 0 }} /* className={inter.className} */>
        <AppRouterCacheProvider>
          <ThemeProvider theme={isDarkTheme ? darkTheme : theme}>
            <Navbar />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
